[package]

name = "tui"
version = "0.1.0"
authors = [ "dmacvicar@gmail.com" ]

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs"

[lib]
name = "tui"
path = "src/lib.rs"

[[bin]]
name = "example1"
path = "src/examples/example1.rs"

